export const FETCH_ALL_DRONES = 'FETCH_ALL_DRONES';
export const FETCH_ALL_DRONES_PENDING = 'FETCH_ALL_DRONES_PENDING';
export const FETCH_ALL_DRONES_FULFILLED = 'FETCH_ALL_DRONES_FULFILLED';
export const FETCH_ALL_DRONES_REJECTED = 'FETCH_ALL_DRONES_REJECTED';
